run:
  # Default timeout is 1m, up to give more room
  timeout: 4m

linters:
  enable:
  - asciicheck
  - bodyclose
  - errorlint
  - gofmt
  - goimports
  - importas
  - misspell
  - nestif
  - prealloc
  - revive
  - stylecheck
  - tparallel
  - unconvert
  - unparam
  - unused
  - whitespace

linters-settings:
  errorlint:
    errorf: false

  importas:
    alias:
  goimports:
    local-prefixes: github.com/operator-framework/deppy

output:
  format: tab
