name: sanity

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.18'
      - name: Run verification checks
        run: make verify
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run golangci linting checks
        uses: golangci/golangci-lint-action@v3
